project:
  type: website
  output-dir: docs

website:
  title: "Adhni"
  reader-mode: true
  navbar:
    logo: "profile.jpeg"
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/adhni
      - icon: linkedin
        href: https://www.linkedin.com/in/adhni/

format:
  html:
    theme: journal
    css: styles.css
    include-after-body: footer.Rhtml



